### ISSUE TITLE
support for @nuxt/typescript-runtime

### ISSUE THREAD

**Issue by nles** [danielroe/nuxt-typed-vuex#29] opened 2019-11-07 10:13 UTC
**🐛 The bug**
If you use @nuxt/typescript-runtime and write your Nuxt configuration in TypeScript (nuxt.config.ts), nuxt-typed-vuex will break in a weird way with pretty much no context or way to debug the issue (see screenshot below)

**🛠️ To reproduce**
1. follow instructions on the Nuxt TypeScript documentation page to set up typescript-runtime and write your config in TypeScript
2. Install and set up nuxt-typed-vuex
3. Run the development server (nuxt-ts)
4. See error: Unexpected Identifier

**ℹ️ Additional context**
![Screenshot 2019-11-07 at 11 57 26](https://user-images.githubusercontent.com/1729955/68380004-ad547f80-0157-11ea-9faa-083ebb37ea89.png)

The exact same configuration, written in JavaScript will work as expected.

Not sure if this relates to nuxt-typed-vuex or Nuxt itself, but leaving it here for someone with more info about how these libraries work together to inspect this further.

**Comment by danielroe** [comment] 2019-11-07 10:40
@nles I really appreciate the bug report. However, I can't reproduce it.

[Here](https://github.com/danielroe/nuxt-typed-vuex-ts-example) is a working example with `@nuxt/typescript-runtime`. Could you throw up a repro, by any chance?

**Comment by danielroe** [comment] 2019-11-08 17:40
@nles To provide a bit more info, I went back to your post and followed the below:

Here are my steps, written out quite explicitly.

1. Install deps
   ```sh
   create-nuxt-app test-app
   cd test-app
   yarn add --dev @nuxt/typescript-build nuxt-typed-vuex
   yarn add @nuxt/typescript-runtime
   ```
2. Rename and edit `nuxt.config` to be typed:
   ```ts
   import { Configuration } from '@nuxt/types'

   const config: Configuration = {
     // ...
     buildModules: ['@nuxt/typescript-build', 'nuxt-typed-vuex'],
     build: {
       transpile: [/nuxt-typed-vuex/],
     },
   }
   
   export default config
   ```
3. Change `nuxt` -> `nuxt-ts` in `package.json`.
4. Add `tsconfig.json` from [here](https://typescript.nuxtjs.org/guide/setup.html#configuration).
5. Add basic `~/store/index.ts`:
   ```ts
   import { getterTree } from 'nuxt-typed-vuex'

   export const state = () => ({})

   export const getters = getterTree(state, {})
   ```

Everything works. However, it's possible something may be lacking in the docs, or you may have a more complicated setup - and I'd be very happy to help. Just send a repro my way!

**Comment by danielroe** [comment] 2019-11-09 09:37
@nles FYI, I've added a Typescript runtime example repo [here](https://nuxt-typed-vuex.danielcroe.com/examples/runtime.html).

**Comment by danielroe** [comment] 2019-11-13 23:38
@nles I'm closing this as I can't reproduce it, but please do come back to me if you have any more information.

**Closed by danielroe** 2019-11-13 23:38 UTC
Labels: bug, needs repro
